import 'package:egnimos/src/utility/font_manager/font_families.dart';
import 'package:egnimos/src/utility/font_manager/font_family_info.dart';

Map<String, FontFamilyInfo Function()> fontsMap() => const {
      // 'ABeeZee': FontFamilies.aBeeZee,
      // 'Abel': FontFamilies.abel,
      // 'Abhaya Libre': FontFamilies.abhayaLibre,
      // 'Abril Fatface': FontFamilies.abrilFatface,
      // 'Aclonica': FontFamilies.aclonica,
      // 'Acme': FontFamilies.acme,
      // 'Actor': FontFamilies.actor,
      // 'Adamina': FontFamilies.adamina,
      // 'Advent Pro': FontFamilies.adventPro,
      // 'Aguafina Script': FontFamilies.aguafinaScript,
      // 'Akaya Kanadaka': FontFamilies.akayaKanadaka,
      // 'Akaya Telivigala': FontFamilies.akayaTelivigala,
      // 'Akronim': FontFamilies.akronim,
      // 'Akshar': FontFamilies.akshar,
      // 'Aladin': FontFamilies.aladin,
      // 'Alata': FontFamilies.alata,
      // 'Alatsi': FontFamilies.alatsi,
      // 'Aldrich': FontFamilies.aldrich,
      // 'Alef': FontFamilies.alef,
      // 'Alegreya': FontFamilies.alegreya,
      // 'Alegreya SC': FontFamilies.alegreyaSc,
      // 'Alegreya Sans': FontFamilies.alegreyaSans,
      // 'Alegreya Sans SC': FontFamilies.alegreyaSansSc,
      // 'Aleo': FontFamilies.aleo,
      // 'Alex Brush': FontFamilies.alexBrush,
      // 'Alfa Slab One': FontFamilies.alfaSlabOne,
      // 'Alice': FontFamilies.alice,
      // 'Alike': FontFamilies.alike,
      // 'Alike Angular': FontFamilies.alikeAngular,
      // 'Allan': FontFamilies.allan,
      // 'Allerta': FontFamilies.allerta,
      // 'Allerta Stencil': FontFamilies.allertaStencil,
      // 'Allison': FontFamilies.allison,
      // 'Allura': FontFamilies.allura,
      // 'Almarai': FontFamilies.almarai,
      // 'Almendra': FontFamilies.almendra,
      // 'Almendra Display': FontFamilies.almendraDisplay,
      // 'Almendra SC': FontFamilies.almendraSc,
      // 'Alumni Sans': FontFamilies.alumniSans,
      // 'Alumni Sans Inline One': FontFamilies.alumniSansInlineOne,
      // 'Amarante': FontFamilies.amarante,
      // 'Amaranth': FontFamilies.amaranth,
      // 'Amatic SC': FontFamilies.amaticSc,
      // 'Amethysta': FontFamilies.amethysta,
      // 'Amiko': FontFamilies.amiko,
      // 'Amiri': FontFamilies.amiri,
      // 'Amita': FontFamilies.amita,
      // 'Anaheim': FontFamilies.anaheim,
      // 'Andada Pro': FontFamilies.andadaPro,
      // 'Andika': FontFamilies.andika,
      // 'Andika New Basic': FontFamilies.andikaNewBasic,
      // 'Anek Bangla': FontFamilies.anekBangla,
      // 'Anek Devanagari': FontFamilies.anekDevanagari,
      // 'Anek Gujarati': FontFamilies.anekGujarati,
      // 'Anek Gurmukhi': FontFamilies.anekGurmukhi,
      // 'Anek Kannada': FontFamilies.anekKannada,
      // 'Anek Latin': FontFamilies.anekLatin,
      // 'Anek Malayalam': FontFamilies.anekMalayalam,
      // 'Anek Odia': FontFamilies.anekOdia,
      // 'Anek Tamil': FontFamilies.anekTamil,
      // 'Anek Telugu': FontFamilies.anekTelugu,
      // 'Angkor': FontFamilies.angkor,
      // 'Annie Use Your Telescope': FontFamilies.annieUseYourTelescope,
      // 'Anonymous Pro': FontFamilies.anonymousPro,
      // 'Antic': FontFamilies.antic,
      // 'Antic Didone': FontFamilies.anticDidone,
      // 'Antic Slab': FontFamilies.anticSlab,
      // 'Anton': FontFamilies.anton,
      // 'Antonio': FontFamilies.antonio,
      // 'Anybody': FontFamilies.anybody,
      // 'Arapey': FontFamilies.arapey,
      // 'Arbutus': FontFamilies.arbutus,
      // 'Arbutus Slab': FontFamilies.arbutusSlab,
      // 'Architects Daughter': FontFamilies.architectsDaughter,
      // 'Archivo': FontFamilies.archivo,
      // 'Archivo Black': FontFamilies.archivoBlack,
      // 'Archivo Narrow': FontFamilies.archivoNarrow,
      // 'Are You Serious': FontFamilies.areYouSerious,
      // 'Aref Ruqaa': FontFamilies.arefRuqaa,
      // 'Arima Madurai': FontFamilies.arimaMadurai,
      // 'Arimo': FontFamilies.arimo,
      // 'Arizonia': FontFamilies.arizonia,
      // 'Armata': FontFamilies.armata,
      // 'Arsenal': FontFamilies.arsenal,
      // 'Artifika': FontFamilies.artifika,
      // 'Arvo': FontFamilies.arvo,
      // 'Arya': FontFamilies.arya,
      // 'Asap': FontFamilies.asap,
      // 'Asap Condensed': FontFamilies.asapCondensed,
      // 'Asar': FontFamilies.asar,
      // 'Asset': FontFamilies.asset,
      // 'Assistant': FontFamilies.assistant,
      // 'Astloch': FontFamilies.astloch,
      // 'Asul': FontFamilies.asul,
      // 'Athiti': FontFamilies.athiti,
      // 'Atkinson Hyperlegible': FontFamilies.atkinsonHyperlegible,
      // 'Atma': FontFamilies.atma,
      // 'Atomic Age': FontFamilies.atomicAge,
      // 'Aubrey': FontFamilies.aubrey,
      // 'Audiowide': FontFamilies.audiowide,
      // 'Autour One': FontFamilies.autourOne,
      // 'Average': FontFamilies.average,
      // 'Average Sans': FontFamilies.averageSans,
      // 'Averia Gruesa Libre': FontFamilies.averiaGruesaLibre,
      // 'Averia Libre': FontFamilies.averiaLibre,
      // 'Averia Sans Libre': FontFamilies.averiaSansLibre,
      // 'Averia Serif Libre': FontFamilies.averiaSerifLibre,
      // 'Azeret Mono': FontFamilies.azeretMono,
      'B612': FontFamilies.b612,
      'B612 Mono': FontFamilies.b612Mono,
      'BIZ UDGothic': FontFamilies.bizUDGothic,
      'BIZ UDMincho': FontFamilies.bizUDMincho,
      'BIZ UDPGothic': FontFamilies.bizUDPGothic,
      'BIZ UDPMincho': FontFamilies.bizUDPMincho,
      'Babylonica': FontFamilies.babylonica,
      'Bad Script': FontFamilies.badScript,
      'Bahiana': FontFamilies.bahiana,
      'Bahianita': FontFamilies.bahianita,
      'Bai Jamjuree': FontFamilies.baiJamjuree,
      'Bakbak One': FontFamilies.bakbakOne,
      'Ballet': FontFamilies.ballet,
      'Baloo 2': FontFamilies.baloo2,
      'Baloo Bhai 2': FontFamilies.balooBhai2,
      'Baloo Bhaijaan 2': FontFamilies.balooBhaijaan2,
      'Baloo Bhaina 2': FontFamilies.balooBhaina2,
      'Baloo Chettan 2': FontFamilies.balooChettan2,
      'Baloo Da 2': FontFamilies.balooDa2,
      'Baloo Paaji 2': FontFamilies.balooPaaji2,
      'Baloo Tamma 2': FontFamilies.balooTamma2,
      'Baloo Tammudu 2': FontFamilies.balooTammudu2,
      'Baloo Thambi 2': FontFamilies.balooThambi2,
      'Balsamiq Sans': FontFamilies.balsamiqSans,
      'Balthazar': FontFamilies.balthazar,
      'Bangers': FontFamilies.bangers,
      'Barlow': FontFamilies.barlow,
      // 'Barlow Condensed': FontFamilies.barlowCondensed,
      // 'Barlow Semi Condensed': FontFamilies.barlowSemiCondensed,
      // 'Barriecito': FontFamilies.barriecito,
      // 'Barrio': FontFamilies.barrio,
      // 'Basic': FontFamilies.basic,
      // 'Baskervville': FontFamilies.baskervville,
      // 'Battambang': FontFamilies.battambang,
      // 'Baumans': FontFamilies.baumans,
      // 'Bayon': FontFamilies.bayon,
      // 'Be Vietnam Pro': FontFamilies.beVietnamPro,
      // 'Beau Rivage': FontFamilies.beauRivage,
      // 'Bebas Neue': FontFamilies.bebasNeue,
      // 'Belgrano': FontFamilies.belgrano,
      // 'Bellefair': FontFamilies.bellefair,
      // 'Belleza': FontFamilies.belleza,
      // 'Bellota': FontFamilies.bellota,
      // 'Bellota Text': FontFamilies.bellotaText,
      // 'BenchNine': FontFamilies.benchNine,
      // 'Benne': FontFamilies.benne,
      // 'Bentham': FontFamilies.bentham,
      // 'Berkshire Swash': FontFamilies.berkshireSwash,
      // 'Besley': FontFamilies.besley,
      // 'Beth Ellen': FontFamilies.bethEllen,
      // 'Bevan': FontFamilies.bevan,
      // 'BhuTuka Expanded One': FontFamilies.bhuTukaExpandedOne,
      // 'Big Shoulders Display': FontFamilies.bigShouldersDisplay,
      // 'Big Shoulders Inline Display': FontFamilies.bigShouldersInlineDisplay,
      // 'Big Shoulders Inline Text': FontFamilies.bigShouldersInlineText,
      // 'Big Shoulders Stencil Display': FontFamilies.bigShouldersStencilDisplay,
      // 'Big Shoulders Stencil Text': FontFamilies.bigShouldersStencilText,
      // 'Big Shoulders Text': FontFamilies.bigShouldersText,
      // 'Bigelow Rules': FontFamilies.bigelowRules,
      // 'Bigshot One': FontFamilies.bigshotOne,
      // 'Bilbo': FontFamilies.bilbo,
      // 'Bilbo Swash Caps': FontFamilies.bilboSwashCaps,
      // 'BioRhyme': FontFamilies.bioRhyme,
      // 'BioRhyme Expanded': FontFamilies.bioRhymeExpanded,
      // 'Birthstone': FontFamilies.birthstone,
      // 'Birthstone Bounce': FontFamilies.birthstoneBounce,
      // 'Biryani': FontFamilies.biryani,
      // 'Bitter': FontFamilies.bitter,
      // 'Black And White Picture': FontFamilies.blackAndWhitePicture,
      // 'Black Han Sans': FontFamilies.blackHanSans,
      // 'Black Ops One': FontFamilies.blackOpsOne,
      // 'Blinker': FontFamilies.blinker,
      // 'Bodoni Moda': FontFamilies.bodoniModa,
      // 'Bokor': FontFamilies.bokor,
      // 'Bona Nova': FontFamilies.bonaNova,
      // 'Bonbon': FontFamilies.bonbon,
      // 'Bonheur Royale': FontFamilies.bonheurRoyale,
      // 'Boogaloo': FontFamilies.boogaloo,
      // 'Bowlby One': FontFamilies.bowlbyOne,
      // 'Bowlby One SC': FontFamilies.bowlbyOneSc,
      // 'Brawler': FontFamilies.brawler,
      // 'Bree Serif': FontFamilies.breeSerif,
      // 'Brygada 1918': FontFamilies.brygada1918,
      // 'Bubblegum Sans': FontFamilies.bubblegumSans,
      // 'Bubbler One': FontFamilies.bubblerOne,
      // 'Buda': FontFamilies.buda,
      // 'Buenard': FontFamilies.buenard,
      // 'Bungee': FontFamilies.bungee,
      // 'Bungee Hairline': FontFamilies.bungeeHairline,
      // 'Bungee Inline': FontFamilies.bungeeInline,
      // 'Bungee Outline': FontFamilies.bungeeOutline,
      // 'Bungee Shade': FontFamilies.bungeeShade,
      // 'Butcherman': FontFamilies.butcherman,
      // 'Butterfly Kids': FontFamilies.butterflyKids,
      'Cabin': FontFamilies.cabin,
      'Cabin Condensed': FontFamilies.cabinCondensed,
      'Cabin Sketch': FontFamilies.cabinSketch,
      'Caesar Dressing': FontFamilies.caesarDressing,
      'Cagliostro': FontFamilies.cagliostro,
      'Cairo': FontFamilies.cairo,
      'Caladea': FontFamilies.caladea,
      'Calistoga': FontFamilies.calistoga,
      // 'Calligraffitti': FontFamilies.calligraffitti,
      'Cambay': FontFamilies.cambay,
      'Cambo': FontFamilies.cambo,
      'Candal': FontFamilies.candal,
      'Cantarell': FontFamilies.cantarell,
      'Cantata One': FontFamilies.cantataOne,
      'Cantora One': FontFamilies.cantoraOne,
      'Capriola': FontFamilies.capriola,
      'Caramel': FontFamilies.caramel,
      'Carattere': FontFamilies.carattere,
      'Cardo': FontFamilies.cardo,
      'Carme': FontFamilies.carme,
      'Carrois Gothic': FontFamilies.carroisGothic,
      'Carrois Gothic SC': FontFamilies.carroisGothicSc,
      'Carter One': FontFamilies.carterOne,
      'Castoro': FontFamilies.castoro,
      'Catamaran': FontFamilies.catamaran,
      'Caudex': FontFamilies.caudex,
      'Caveat': FontFamilies.caveat,
      'Caveat Brush': FontFamilies.caveatBrush,
      'Cedarville Cursive': FontFamilies.cedarvilleCursive,
      'Ceviche One': FontFamilies.cevicheOne,
      'Chakra Petch': FontFamilies.chakraPetch,
      'Changa': FontFamilies.changa,
      'Changa One': FontFamilies.changaOne,
      'Chango': FontFamilies.chango,
      'Charm': FontFamilies.charm,
      // 'Charmonman': FontFamilies.charmonman,
      // 'Chathura': FontFamilies.chathura,
      // 'Chau Philomene One': FontFamilies.chauPhilomeneOne,
      // 'Chela One': FontFamilies.chelaOne,
      // 'Chelsea Market': FontFamilies.chelseaMarket,
      // 'Chenla': FontFamilies.chenla,
      // 'Cherish': FontFamilies.cherish,
      // 'Cherry Cream Soda': FontFamilies.cherryCreamSoda,
      // 'Cherry Swash': FontFamilies.cherrySwash,
      // 'Chewy': FontFamilies.chewy,
      // 'Chicle': FontFamilies.chicle,
      // 'Chilanka': FontFamilies.chilanka,
      // 'Chivo': FontFamilies.chivo,
      // 'Chonburi': FontFamilies.chonburi,
      // 'Cinzel': FontFamilies.cinzel,
      // 'Cinzel Decorative': FontFamilies.cinzelDecorative,
      // 'Clicker Script': FontFamilies.clickerScript,
      // 'Coda': FontFamilies.coda,
      // 'Coda Caption': FontFamilies.codaCaption,
      // 'Codystar': FontFamilies.codystar,
      // 'Coiny': FontFamilies.coiny,
      // 'Combo': FontFamilies.combo,
      // 'Comfortaa': FontFamilies.comfortaa,
      // 'Comforter': FontFamilies.comforter,
      // 'Comforter Brush': FontFamilies.comforterBrush,
      // 'Comic Neue': FontFamilies.comicNeue,
      // 'Coming Soon': FontFamilies.comingSoon,
      // 'Commissioner': FontFamilies.commissioner,
      // 'Concert One': FontFamilies.concertOne,
      // 'Condiment': FontFamilies.condiment,
      // 'Content': FontFamilies.content,
      // 'Contrail One': FontFamilies.contrailOne,
      // 'Convergence': FontFamilies.convergence,
      // 'Cookie': FontFamilies.cookie,
      // 'Copse': FontFamilies.copse,
      // 'Corben': FontFamilies.corben,
      // 'Corinthia': FontFamilies.corinthia,
      // 'Cormorant': FontFamilies.cormorant,
      // 'Cormorant Garamond': FontFamilies.cormorantGaramond,
      // 'Cormorant Infant': FontFamilies.cormorantInfant,
      // 'Cormorant SC': FontFamilies.cormorantSc,
      // 'Cormorant Unicase': FontFamilies.cormorantUnicase,
      // 'Cormorant Upright': FontFamilies.cormorantUpright,
      // 'Courgette': FontFamilies.courgette,
      // 'Courier Prime': FontFamilies.courierPrime,
      // 'Cousine': FontFamilies.cousine,
      // 'Coustard': FontFamilies.coustard,
      // 'Covered By Your Grace': FontFamilies.coveredByYourGrace,
      // 'Crafty Girls': FontFamilies.craftyGirls,
      // 'Creepster': FontFamilies.creepster,
      // 'Crete Round': FontFamilies.creteRound,
      // 'Crimson Pro': FontFamilies.crimsonPro,
      // 'Croissant One': FontFamilies.croissantOne,
      // 'Crushed': FontFamilies.crushed,
      // 'Cuprum': FontFamilies.cuprum,
      // 'Cute Font': FontFamilies.cuteFont,
      // 'Cutive': FontFamilies.cutive,
      // 'Cutive Mono': FontFamilies.cutiveMono,
      // 'DM Mono': FontFamilies.dmMono,
      // 'DM Sans': FontFamilies.dmSans,
      // 'DM Serif Display': FontFamilies.dmSerifDisplay,
      // 'DM Serif Text': FontFamilies.dmSerifText,
      // 'Damion': FontFamilies.damion,
      // 'Dancing Script': FontFamilies.dancingScript,
      // 'Dangrek': FontFamilies.dangrek,
      // 'Darker Grotesque': FontFamilies.darkerGrotesque,
      // 'David Libre': FontFamilies.davidLibre,
      // 'Dawning of a New Day': FontFamilies.dawningOfANewDay,
      // 'Days One': FontFamilies.daysOne,
      // 'Dekko': FontFamilies.dekko,
      // 'Dela Gothic One': FontFamilies.delaGothicOne,
      // 'Delius': FontFamilies.delius,
      // 'Delius Swash Caps': FontFamilies.deliusSwashCaps,
      // 'Delius Unicase': FontFamilies.deliusUnicase,
      // 'Della Respira': FontFamilies.dellaRespira,
      // 'Denk One': FontFamilies.denkOne,
      // 'Devonshire': FontFamilies.devonshire,
      // 'Dhurjati': FontFamilies.dhurjati,
      // 'Didact Gothic': FontFamilies.didactGothic,
      // 'Diplomata': FontFamilies.diplomata,
      // 'Diplomata SC': FontFamilies.diplomataSc,
      // 'Do Hyeon': FontFamilies.doHyeon,
      // 'Dokdo': FontFamilies.dokdo,
      // 'Domine': FontFamilies.domine,
      // 'Donegal One': FontFamilies.donegalOne,
      // 'Dongle': FontFamilies.dongle,
      // 'Doppio One': FontFamilies.doppioOne,
      // 'Dorsa': FontFamilies.dorsa,
      // 'Dosis': FontFamilies.dosis,
      // 'DotGothic16': FontFamilies.dotGothic16,
      // 'Dr Sugiyama': FontFamilies.drSugiyama,
      // 'Duru Sans': FontFamilies.duruSans,
      // 'Dynalight': FontFamilies.dynalight,
      // 'EB Garamond': FontFamilies.ebGaramond,
      // 'Eagle Lake': FontFamilies.eagleLake,
      // 'East Sea Dokdo': FontFamilies.eastSeaDokdo,
      // 'Eater': FontFamilies.eater,
      // 'Economica': FontFamilies.economica,
      // 'Eczar': FontFamilies.eczar,
      // 'El Messiri': FontFamilies.elMessiri,
      // 'Electrolize': FontFamilies.electrolize,
      // 'Elsie': FontFamilies.elsie,
      // 'Elsie Swash Caps': FontFamilies.elsieSwashCaps,
      // 'Emblema One': FontFamilies.emblemaOne,
      // 'Emilys Candy': FontFamilies.emilysCandy,
      // 'Encode Sans': FontFamilies.encodeSans,
      // 'Encode Sans Condensed': FontFamilies.encodeSansCondensed,
      // 'Encode Sans Expanded': FontFamilies.encodeSansExpanded,
      // 'Encode Sans SC': FontFamilies.encodeSansSc,
      // 'Encode Sans Semi Condensed': FontFamilies.encodeSansSemiCondensed,
      // 'Encode Sans Semi Expanded': FontFamilies.encodeSansSemiExpanded,
      // 'Engagement': FontFamilies.engagement,
      // 'Englebert': FontFamilies.englebert,
      // 'Enriqueta': FontFamilies.enriqueta,
      // 'Ephesis': FontFamilies.ephesis,
      // 'Epilogue': FontFamilies.epilogue,
      // 'Erica One': FontFamilies.ericaOne,
      // 'Esteban': FontFamilies.esteban,
      // 'Estonia': FontFamilies.estonia,
      // 'Euphoria Script': FontFamilies.euphoriaScript,
      // 'Ewert': FontFamilies.ewert,
      // 'Exo': FontFamilies.exo,
      // 'Exo 2': FontFamilies.exo2,
      // 'Expletus Sans': FontFamilies.expletusSans,
      // 'Explora': FontFamilies.explora,
      // 'Fahkwang': FontFamilies.fahkwang,
      // 'Familjen Grotesk': FontFamilies.familjenGrotesk,
      // 'Fanwood Text': FontFamilies.fanwoodText,
      // 'Farro': FontFamilies.farro,
      // 'Farsan': FontFamilies.farsan,
      // 'Fascinate': FontFamilies.fascinate,
      // 'Fascinate Inline': FontFamilies.fascinateInline,
      // 'Faster One': FontFamilies.fasterOne,
      // 'Fasthand': FontFamilies.fasthand,
      // 'Fauna One': FontFamilies.faunaOne,
      // 'Faustina': FontFamilies.faustina,
      // 'Federant': FontFamilies.federant,
      // 'Federo': FontFamilies.federo,
      // 'Felipa': FontFamilies.felipa,
      // 'Fenix': FontFamilies.fenix,
      // 'Festive': FontFamilies.festive,
      // 'Finger Paint': FontFamilies.fingerPaint,
      // 'Fira Code': FontFamilies.firaCode,
      // 'Fira Mono': FontFamilies.firaMono,
      // 'Fira Sans': FontFamilies.firaSans,
      // 'Fira Sans Condensed': FontFamilies.firaSansCondensed,
      // 'Fira Sans Extra Condensed': FontFamilies.firaSansExtraCondensed,
      // 'Fjalla One': FontFamilies.fjallaOne,
      // 'Fjord One': FontFamilies.fjordOne,
      // 'Flamenco': FontFamilies.flamenco,
      // 'Flavors': FontFamilies.flavors,
      // 'Fleur De Leah': FontFamilies.fleurDeLeah,
      // 'Flow Block': FontFamilies.flowBlock,
      // 'Flow Circular': FontFamilies.flowCircular,
      // 'Flow Rounded': FontFamilies.flowRounded,
      // 'Fondamento': FontFamilies.fondamento,
      // 'Fontdiner Swanky': FontFamilies.fontdinerSwanky,
      // 'Forum': FontFamilies.forum,
      // 'Francois One': FontFamilies.francoisOne,
      // 'Frank Ruhl Libre': FontFamilies.frankRuhlLibre,
      // 'Fraunces': FontFamilies.fraunces,
      // 'Freckle Face': FontFamilies.freckleFace,
      // 'Fredericka the Great': FontFamilies.frederickaTheGreat,
      // 'Fredoka': FontFamilies.fredoka,
      // 'Fredoka One': FontFamilies.fredokaOne,
      // 'Freehand': FontFamilies.freehand,
      // 'Fresca': FontFamilies.fresca,
      // 'Frijole': FontFamilies.frijole,
      // 'Fruktur': FontFamilies.fruktur,
      // 'Fugaz One': FontFamilies.fugazOne,
      // 'Fuggles': FontFamilies.fuggles,
      // 'Fuzzy Bubbles': FontFamilies.fuzzyBubbles,
      // 'GFS Didot': FontFamilies.gfsDidot,
      // 'GFS Neohellenic': FontFamilies.gfsNeohellenic,
      // 'Gabriela': FontFamilies.gabriela,
      // 'Gaegu': FontFamilies.gaegu,
      // 'Gafata': FontFamilies.gafata,
      // 'Galada': FontFamilies.galada,
      // 'Galdeano': FontFamilies.galdeano,
      // 'Galindo': FontFamilies.galindo,
      // 'Gamja Flower': FontFamilies.gamjaFlower,
      // 'Gayathri': FontFamilies.gayathri,
      // 'Gelasio': FontFamilies.gelasio,
      // 'Gemunu Libre': FontFamilies.gemunuLibre,
      // 'Genos': FontFamilies.genos,
      // 'Gentium Basic': FontFamilies.gentiumBasic,
      // 'Gentium Book Basic': FontFamilies.gentiumBookBasic,
      // 'Geo': FontFamilies.geo,
      // 'Georama': FontFamilies.georama,
      // 'Geostar': FontFamilies.geostar,
      // 'Geostar Fill': FontFamilies.geostarFill,
      // 'Germania One': FontFamilies.germaniaOne,
      // 'Gideon Roman': FontFamilies.gideonRoman,
      // 'Gidugu': FontFamilies.gidugu,
      // 'Gilda Display': FontFamilies.gildaDisplay,
      // 'Girassol': FontFamilies.girassol,
      // 'Give You Glory': FontFamilies.giveYouGlory,
      // 'Glass Antiqua': FontFamilies.glassAntiqua,
      // 'Glegoo': FontFamilies.glegoo,
      // 'Gloria Hallelujah': FontFamilies.gloriaHallelujah,
      // 'Glory': FontFamilies.glory,
      // 'Gluten': FontFamilies.gluten,
      // 'Goblin One': FontFamilies.goblinOne,
      // 'Gochi Hand': FontFamilies.gochiHand,
      // 'Goldman': FontFamilies.goldman,
      // 'Gorditas': FontFamilies.gorditas,
      // 'Gothic A1': FontFamilies.gothicA1,
      // 'Gotu': FontFamilies.gotu,
      // 'Goudy Bookletter 1911': FontFamilies.goudyBookletter1911,
      // 'Gowun Batang': FontFamilies.gowunBatang,
      // 'Gowun Dodum': FontFamilies.gowunDodum,
      // 'Graduate': FontFamilies.graduate,
      // 'Grand Hotel': FontFamilies.grandHotel,
      // 'Grandstander': FontFamilies.grandstander,
      // 'Grape Nuts': FontFamilies.grapeNuts,
      // 'Gravitas One': FontFamilies.gravitasOne,
      // 'Great Vibes': FontFamilies.greatVibes,
      // 'Grechen Fuemen': FontFamilies.grechenFuemen,
      // 'Grenze': FontFamilies.grenze,
      // 'Grenze Gotisch': FontFamilies.grenzeGotisch,
      // 'Grey Qo': FontFamilies.greyQo,
      // 'Griffy': FontFamilies.griffy,
      // 'Gruppo': FontFamilies.gruppo,
      // 'Gudea': FontFamilies.gudea,
      // 'Gugi': FontFamilies.gugi,
      // 'Gupter': FontFamilies.gupter,
      // 'Gurajada': FontFamilies.gurajada,
      // 'Gwendolyn': FontFamilies.gwendolyn,
      // 'Habibi': FontFamilies.habibi,
      // 'Hachi Maru Pop': FontFamilies.hachiMaruPop,
      // 'Hahmlet': FontFamilies.hahmlet,
      // 'Halant': FontFamilies.halant,
      // 'Hammersmith One': FontFamilies.hammersmithOne,
      // 'Hanalei': FontFamilies.hanalei,
      // 'Hanalei Fill': FontFamilies.hanaleiFill,
      // 'Handlee': FontFamilies.handlee,
      // 'Hanuman': FontFamilies.hanuman,
      // 'Happy Monkey': FontFamilies.happyMonkey,
      // 'Harmattan': FontFamilies.harmattan,
      // 'Headland One': FontFamilies.headlandOne,
      // 'Heebo': FontFamilies.heebo,
      // 'Henny Penny': FontFamilies.hennyPenny,
      // 'Hepta Slab': FontFamilies.heptaSlab,
      // 'Herr Von Muellerhoff': FontFamilies.herrVonMuellerhoff,
      // 'Hi Melody': FontFamilies.hiMelody,
      // 'Hina Mincho': FontFamilies.hinaMincho,
      // 'Hind': FontFamilies.hind,
      // 'Hind Guntur': FontFamilies.hindGuntur,
      // 'Hind Madurai': FontFamilies.hindMadurai,
      // 'Hind Siliguri': FontFamilies.hindSiliguri,
      // 'Hind Vadodara': FontFamilies.hindVadodara,
      // 'Holtwood One SC': FontFamilies.holtwoodOneSc,
      // 'Homemade Apple': FontFamilies.homemadeApple,
      // 'Homenaje': FontFamilies.homenaje,
      // 'Hubballi': FontFamilies.hubballi,
      // 'Hurricane': FontFamilies.hurricane,
      // 'IBM Plex Mono': FontFamilies.ibmPlexMono,
      // 'IBM Plex Sans': FontFamilies.ibmPlexSans,
      // 'IBM Plex Sans Arabic': FontFamilies.ibmPlexSansArabic,
      // 'IBM Plex Sans Condensed': FontFamilies.ibmPlexSansCondensed,
      // 'IBM Plex Sans Devanagari': FontFamilies.ibmPlexSansDevanagari,
      // 'IBM Plex Sans Hebrew': FontFamilies.ibmPlexSansHebrew,
      // 'IBM Plex Sans KR': FontFamilies.ibmPlexSansKr,
      // 'IBM Plex Sans Thai': FontFamilies.ibmPlexSansThai,
      // 'IBM Plex Sans Thai Looped': FontFamilies.ibmPlexSansThaiLooped,
      // 'IBM Plex Serif': FontFamilies.ibmPlexSerif,
      // 'IM Fell DW Pica': FontFamilies.imFellDwPica,
      // 'IM Fell DW Pica SC': FontFamilies.imFellDwPicaSc,
      // 'IM Fell Double Pica': FontFamilies.imFellDoublePica,
      // 'IM Fell Double Pica SC': FontFamilies.imFellDoublePicaSc,
      // 'IM Fell English': FontFamilies.imFellEnglish,
      // 'IM Fell English SC': FontFamilies.imFellEnglishSc,
      // 'IM Fell French Canon': FontFamilies.imFellFrenchCanon,
      // 'IM Fell French Canon SC': FontFamilies.imFellFrenchCanonSc,
      // 'IM Fell Great Primer': FontFamilies.imFellGreatPrimer,
      // 'IM Fell Great Primer SC': FontFamilies.imFellGreatPrimerSc,
      // 'Ibarra Real Nova': FontFamilies.ibarraRealNova,
      // 'Iceberg': FontFamilies.iceberg,
      // 'Iceland': FontFamilies.iceland,
      // 'Imbue': FontFamilies.imbue,
      // 'Imperial Script': FontFamilies.imperialScript,
      // 'Imprima': FontFamilies.imprima,
      // 'Inconsolata': FontFamilies.inconsolata,
      // 'Inder': FontFamilies.inder,
      // 'Indie Flower': FontFamilies.indieFlower,
      // 'Ingrid Darling': FontFamilies.ingridDarling,
      // 'Inika': FontFamilies.inika,
      // 'Inknut Antiqua': FontFamilies.inknutAntiqua,
      // 'Inria Sans': FontFamilies.inriaSans,
      // 'Inria Serif': FontFamilies.inriaSerif,
      // 'Inspiration': FontFamilies.inspiration,
      // 'Inter': FontFamilies.inter,
      // 'Irish Grover': FontFamilies.irishGrover,
      // 'Island Moments': FontFamilies.islandMoments,
      // 'Istok Web': FontFamilies.istokWeb,
      // 'Italiana': FontFamilies.italiana,
      // 'Italianno': FontFamilies.italianno,
      // 'Itim': FontFamilies.itim,
      // 'Jacques Francois': FontFamilies.jacquesFrancois,
      // 'Jacques Francois Shadow': FontFamilies.jacquesFrancoisShadow,
      // 'Jaldi': FontFamilies.jaldi,
      // 'JetBrains Mono': FontFamilies.jetBrainsMono,
      // 'Jim Nightshade': FontFamilies.jimNightshade,
      // 'Jockey One': FontFamilies.jockeyOne,
      // 'Jolly Lodger': FontFamilies.jollyLodger,
      // 'Jomhuria': FontFamilies.jomhuria,
      // 'Jomolhari': FontFamilies.jomolhari,
      // 'Josefin Sans': FontFamilies.josefinSans,
      // 'Josefin Slab': FontFamilies.josefinSlab,
      // 'Jost': FontFamilies.jost,
      // 'Joti One': FontFamilies.jotiOne,
      // 'Jua': FontFamilies.jua,
      // 'Judson': FontFamilies.judson,
      // 'Julee': FontFamilies.julee,
      // 'Julius Sans One': FontFamilies.juliusSansOne,
      // 'Junge': FontFamilies.junge,
      // 'Jura': FontFamilies.jura,
      // 'Just Another Hand': FontFamilies.justAnotherHand,
      // 'Just Me Again Down Here': FontFamilies.justMeAgainDownHere,
      // 'K2D': FontFamilies.k2d,
      // 'Kadwa': FontFamilies.kadwa,
      // 'Kaisei Decol': FontFamilies.kaiseiDecol,
      // 'Kaisei HarunoUmi': FontFamilies.kaiseiHarunoUmi,
      // 'Kaisei Opti': FontFamilies.kaiseiOpti,
      // 'Kaisei Tokumin': FontFamilies.kaiseiTokumin,
      // 'Kalam': FontFamilies.kalam,
      // 'Kameron': FontFamilies.kameron,
      // 'Kanit': FontFamilies.kanit,
      // 'Kantumruy': FontFamilies.kantumruy,
      // 'Karantina': FontFamilies.karantina,
      // 'Karla': FontFamilies.karla,
      // 'Karma': FontFamilies.karma,
      // 'Katibeh': FontFamilies.katibeh,
      // 'Kaushan Script': FontFamilies.kaushanScript,
      // 'Kavivanar': FontFamilies.kavivanar,
      // 'Kavoon': FontFamilies.kavoon,
      // 'Kdam Thmor': FontFamilies.kdamThmor,
      // 'Keania One': FontFamilies.keaniaOne,
      // 'Kelly Slab': FontFamilies.kellySlab,
      // 'Kenia': FontFamilies.kenia,
      // 'Khand': FontFamilies.khand,
      // 'Khmer': FontFamilies.khmer,
      // 'Khula': FontFamilies.khula,
      // 'Kings': FontFamilies.kings,
      // 'Kirang Haerang': FontFamilies.kirangHaerang,
      // 'Kite One': FontFamilies.kiteOne,
      // 'Kiwi Maru': FontFamilies.kiwiMaru,
      // 'Klee One': FontFamilies.kleeOne,
      // 'Knewave': FontFamilies.knewave,
      // 'KoHo': FontFamilies.koHo,
      // 'Kodchasan': FontFamilies.kodchasan,
      // 'Koh Santepheap': FontFamilies.kohSantepheap,
      // 'Kolker Brush': FontFamilies.kolkerBrush,
      // 'Kosugi': FontFamilies.kosugi,
      // 'Kosugi Maru': FontFamilies.kosugiMaru,
      // 'Kotta One': FontFamilies.kottaOne,
      // 'Koulen': FontFamilies.koulen,
      // 'Kranky': FontFamilies.kranky,
      // 'Kreon': FontFamilies.kreon,
      // 'Kristi': FontFamilies.kristi,
      // 'Krona One': FontFamilies.kronaOne,
      // 'Krub': FontFamilies.krub,
      // 'Kufam': FontFamilies.kufam,
      // 'Kulim Park': FontFamilies.kulimPark,
      // 'Kumar One': FontFamilies.kumarOne,
      // 'Kumar One Outline': FontFamilies.kumarOneOutline,
      // 'Kumbh Sans': FontFamilies.kumbhSans,
      // 'Kurale': FontFamilies.kurale,
      // 'La Belle Aurore': FontFamilies.laBelleAurore,
      // 'Lacquer': FontFamilies.lacquer,
      // 'Laila': FontFamilies.laila,
      // 'Lakki Reddy': FontFamilies.lakkiReddy,
      // 'Lalezar': FontFamilies.lalezar,
      // 'Lancelot': FontFamilies.lancelot,
      // 'Langar': FontFamilies.langar,
      // 'Lateef': FontFamilies.lateef,
      // 'Lato': FontFamilies.lato,
      // 'Lavishly Yours': FontFamilies.lavishlyYours,
      // 'League Gothic': FontFamilies.leagueGothic,
      // 'League Script': FontFamilies.leagueScript,
      // 'League Spartan': FontFamilies.leagueSpartan,
      // 'Leckerli One': FontFamilies.leckerliOne,
      // 'Ledger': FontFamilies.ledger,
      // 'Lekton': FontFamilies.lekton,
      // 'Lemon': FontFamilies.lemon,
      // 'Lemonada': FontFamilies.lemonada,
      // 'Lexend': FontFamilies.lexend,
      // 'Lexend Deca': FontFamilies.lexendDeca,
      // 'Lexend Exa': FontFamilies.lexendExa,
      // 'Lexend Giga': FontFamilies.lexendGiga,
      // 'Lexend Mega': FontFamilies.lexendMega,
      // 'Lexend Peta': FontFamilies.lexendPeta,
      // 'Lexend Tera': FontFamilies.lexendTera,
      // 'Lexend Zetta': FontFamilies.lexendZetta,
      // 'Libre Barcode 128': FontFamilies.libreBarcode128,
      // 'Libre Barcode 128 Text': FontFamilies.libreBarcode128Text,
      // 'Libre Barcode 39': FontFamilies.libreBarcode39,
      // 'Libre Barcode 39 Extended': FontFamilies.libreBarcode39Extended,
      // 'Libre Barcode 39 Extended Text':
      //     FontFamilies.libreBarcode39ExtendedText,
      // 'Libre Barcode 39 Text': FontFamilies.libreBarcode39Text,
      // 'Libre Barcode EAN13 Text': FontFamilies.libreBarcodeEan13Text,
      // 'Libre Baskerville': FontFamilies.libreBaskerville,
      // 'Libre Bodoni': FontFamilies.libreBodoni,
      // 'Libre Caslon Display': FontFamilies.libreCaslonDisplay,
      // 'Libre Caslon Text': FontFamilies.libreCaslonText,
      // 'Libre Franklin': FontFamilies.libreFranklin,
      // 'Licorice': FontFamilies.licorice,
      // 'Life Savers': FontFamilies.lifeSavers,
      // 'Lilita One': FontFamilies.lilitaOne,
      // 'Lily Script One': FontFamilies.lilyScriptOne,
      // 'Limelight': FontFamilies.limelight,
      // 'Linden Hill': FontFamilies.lindenHill,
      // 'Literata': FontFamilies.literata,
      // 'Liu Jian Mao Cao': FontFamilies.liuJianMaoCao,
      // 'Livvic': FontFamilies.livvic,
      // 'Lobster': FontFamilies.lobster,
      // 'Lobster Two': FontFamilies.lobsterTwo,
      // 'Londrina Outline': FontFamilies.londrinaOutline,
      // 'Londrina Shadow': FontFamilies.londrinaShadow,
      // 'Londrina Sketch': FontFamilies.londrinaSketch,
      // 'Londrina Solid': FontFamilies.londrinaSolid,
      // 'Long Cang': FontFamilies.longCang,
      // 'Lora': FontFamilies.lora,
      // 'Love Light': FontFamilies.loveLight,
      // 'Love Ya Like A Sister': FontFamilies.loveYaLikeASister,
      // 'Loved by the King': FontFamilies.lovedByTheKing,
      // 'Lovers Quarrel': FontFamilies.loversQuarrel,
      // 'Luckiest Guy': FontFamilies.luckiestGuy,
      // 'Lusitana': FontFamilies.lusitana,
      // 'Lustria': FontFamilies.lustria,
      // 'Luxurious Roman': FontFamilies.luxuriousRoman,
      // 'Luxurious Script': FontFamilies.luxuriousScript,
      // 'M PLUS 1': FontFamilies.mPlus1,
      // 'M PLUS 1 Code': FontFamilies.mPlus1Code,
      // 'M PLUS 1p': FontFamilies.mPlus1p,
      // 'M PLUS 2': FontFamilies.mPlus2,
      // 'M PLUS Code Latin': FontFamilies.mPlusCodeLatin,
      // 'M PLUS Rounded 1c': FontFamilies.mPlusRounded1c,
      // 'Ma Shan Zheng': FontFamilies.maShanZheng,
      // 'Macondo': FontFamilies.macondo,
      // 'Macondo Swash Caps': FontFamilies.macondoSwashCaps,
      // 'Mada': FontFamilies.mada,
      // 'Magra': FontFamilies.magra,
      // 'Maiden Orange': FontFamilies.maidenOrange,
      // 'Maitree': FontFamilies.maitree,
      // 'Major Mono Display': FontFamilies.majorMonoDisplay,
      // 'Mako': FontFamilies.mako,
      // 'Mali': FontFamilies.mali,
      // 'Mallanna': FontFamilies.mallanna,
      // 'Mandali': FontFamilies.mandali,
      // 'Manjari': FontFamilies.manjari,
      // 'Manrope': FontFamilies.manrope,
      // 'Mansalva': FontFamilies.mansalva,
      // 'Manuale': FontFamilies.manuale,
      // 'Marcellus': FontFamilies.marcellus,
      // 'Marcellus SC': FontFamilies.marcellusSc,
      // 'Marck Script': FontFamilies.marckScript,
      // 'Margarine': FontFamilies.margarine,
      // 'Markazi Text': FontFamilies.markaziText,
      // 'Marko One': FontFamilies.markoOne,
      // 'Marmelad': FontFamilies.marmelad,
      // 'Martel': FontFamilies.martel,
      // 'Martel Sans': FontFamilies.martelSans,
      // 'Marvel': FontFamilies.marvel,
      // 'Mate': FontFamilies.mate,
      // 'Mate SC': FontFamilies.mateSc,
      // 'Maven Pro': FontFamilies.mavenPro,
      // 'McLaren': FontFamilies.mcLaren,
      // 'Mea Culpa': FontFamilies.meaCulpa,
      // 'Meddon': FontFamilies.meddon,
      // 'MedievalSharp': FontFamilies.medievalSharp,
      // 'Medula One': FontFamilies.medulaOne,
      // 'Meera Inimai': FontFamilies.meeraInimai,
      // 'Megrim': FontFamilies.megrim,
      // 'Meie Script': FontFamilies.meieScript,
      // 'Meow Script': FontFamilies.meowScript,
      // 'Merienda': FontFamilies.merienda,
      // 'Merienda One': FontFamilies.meriendaOne,
      // 'Merriweather': FontFamilies.merriweather,
      // 'Merriweather Sans': FontFamilies.merriweatherSans,
      // 'Metal': FontFamilies.metal,
      // 'Metal Mania': FontFamilies.metalMania,
      // 'Metamorphous': FontFamilies.metamorphous,
      // 'Metrophobic': FontFamilies.metrophobic,
      // 'Michroma': FontFamilies.michroma,
      // 'Milonga': FontFamilies.milonga,
      // 'Miltonian': FontFamilies.miltonian,
      // 'Miltonian Tattoo': FontFamilies.miltonianTattoo,
      // 'Mina': FontFamilies.mina,
      // 'Miniver': FontFamilies.miniver,
      // 'Miriam Libre': FontFamilies.miriamLibre,
      // 'Mirza': FontFamilies.mirza,
      // 'Miss Fajardose': FontFamilies.missFajardose,
      // 'Mitr': FontFamilies.mitr,
      // 'Mochiy Pop One': FontFamilies.mochiyPopOne,
      // 'Mochiy Pop P One': FontFamilies.mochiyPopPOne,
      // 'Modak': FontFamilies.modak,
      // 'Modern Antiqua': FontFamilies.modernAntiqua,
      // 'Mogra': FontFamilies.mogra,
      // 'Mohave': FontFamilies.mohave,
      // 'Molengo': FontFamilies.molengo,
      // 'Molle': FontFamilies.molle,
      // 'Monda': FontFamilies.monda,
      // 'Monofett': FontFamilies.monofett,
      // 'Monoton': FontFamilies.monoton,
      // 'Monsieur La Doulaise': FontFamilies.monsieurLaDoulaise,
      // 'Montaga': FontFamilies.montaga,
      // 'Montagu Slab': FontFamilies.montaguSlab,
      // 'MonteCarlo': FontFamilies.monteCarlo,
      // 'Montez': FontFamilies.montez,
      // 'Montserrat': FontFamilies.montserrat,
      // 'Montserrat Alternates': FontFamilies.montserratAlternates,
      // 'Montserrat Subrayada': FontFamilies.montserratSubrayada,
      // 'Moo Lah Lah': FontFamilies.mooLahLah,
      // 'Moon Dance': FontFamilies.moonDance,
      // 'Moul': FontFamilies.moul,
      // 'Moulpali': FontFamilies.moulpali,
      // 'Mountains of Christmas': FontFamilies.mountainsOfChristmas,
      // 'Mouse Memoirs': FontFamilies.mouseMemoirs,
      // 'Mr Bedfort': FontFamilies.mrBedfort,
      // 'Mr Dafoe': FontFamilies.mrDafoe,
      // 'Mr De Haviland': FontFamilies.mrDeHaviland,
      // 'Mrs Saint Delafield': FontFamilies.mrsSaintDelafield,
      // 'Mrs Sheppards': FontFamilies.mrsSheppards,
      // 'Ms Madi': FontFamilies.msMadi,
      // 'Mukta': FontFamilies.mukta,
      // 'Mukta Mahee': FontFamilies.muktaMahee,
      // 'Mukta Malar': FontFamilies.muktaMalar,
      // 'Mukta Vaani': FontFamilies.muktaVaani,
      // 'Mulish': FontFamilies.mulish,
      // 'Murecho': FontFamilies.murecho,
      // 'MuseoModerno': FontFamilies.museoModerno,
      // 'My Soul': FontFamilies.mySoul,
      // 'Mystery Quest': FontFamilies.mysteryQuest,
      // 'NTR': FontFamilies.ntr,
      // 'Nanum Brush Script': FontFamilies.nanumBrushScript,
      // 'Nanum Gothic': FontFamilies.nanumGothic,
      // 'Nanum Gothic Coding': FontFamilies.nanumGothicCoding,
      // 'Nanum Myeongjo': FontFamilies.nanumMyeongjo,
      // 'Nanum Pen Script': FontFamilies.nanumPenScript,
      // 'Neonderthaw': FontFamilies.neonderthaw,
      // 'Nerko One': FontFamilies.nerkoOne,
      // 'Neucha': FontFamilies.neucha,
      // 'Neuton': FontFamilies.neuton,
      // 'New Rocker': FontFamilies.newRocker,
      // 'New Tegomin': FontFamilies.newTegomin,
      // 'News Cycle': FontFamilies.newsCycle,
      // 'Newsreader': FontFamilies.newsreader,
      // 'Niconne': FontFamilies.niconne,
      // 'Niramit': FontFamilies.niramit,
      // 'Nixie One': FontFamilies.nixieOne,
      // 'Nobile': FontFamilies.nobile,
      // 'Nokora': FontFamilies.nokora,
      // 'Norican': FontFamilies.norican,
      // 'Nosifer': FontFamilies.nosifer,
      // 'Notable': FontFamilies.notable,
      // 'Nothing You Could Do': FontFamilies.nothingYouCouldDo,
      // 'Noticia Text': FontFamilies.noticiaText,
      // 'Noto Emoji': FontFamilies.notoEmoji,
      // 'Noto Kufi Arabic': FontFamilies.notoKufiArabic,
      // 'Noto Music': FontFamilies.notoMusic,
      // 'Noto Naskh Arabic': FontFamilies.notoNaskhArabic,
      // 'Noto Nastaliq Urdu': FontFamilies.notoNastaliqUrdu,
      // 'Noto Rashi Hebrew': FontFamilies.notoRashiHebrew,
      // 'Noto Sans': FontFamilies.notoSans,
      // 'Noto Sans Adlam': FontFamilies.notoSansAdlam,
      // 'Noto Sans Adlam Unjoined': FontFamilies.notoSansAdlamUnjoined,
      // 'Noto Sans Anatolian Hieroglyphs':
      //     FontFamilies.notoSansAnatolianHieroglyphs,
      // 'Noto Sans Arabic': FontFamilies.notoSansArabic,
      // 'Noto Sans Armenian': FontFamilies.notoSansArmenian,
      // 'Noto Sans Avestan': FontFamilies.notoSansAvestan,
      // 'Noto Sans Balinese': FontFamilies.notoSansBalinese,
      // 'Noto Sans Bamum': FontFamilies.notoSansBamum,
      // 'Noto Sans Bassa Vah': FontFamilies.notoSansBassaVah,
      // 'Noto Sans Batak': FontFamilies.notoSansBatak,
      // 'Noto Sans Bengali': FontFamilies.notoSansBengali,
      // 'Noto Sans Bhaiksuki': FontFamilies.notoSansBhaiksuki,
      // 'Noto Sans Brahmi': FontFamilies.notoSansBrahmi,
      // 'Noto Sans Buginese': FontFamilies.notoSansBuginese,
      // 'Noto Sans Buhid': FontFamilies.notoSansBuhid,
      // 'Noto Sans Canadian Aboriginal': FontFamilies.notoSansCanadianAboriginal,
      // 'Noto Sans Carian': FontFamilies.notoSansCarian,
      // 'Noto Sans Caucasian Albanian': FontFamilies.notoSansCaucasianAlbanian,
      // 'Noto Sans Chakma': FontFamilies.notoSansChakma,
      // 'Noto Sans Cham': FontFamilies.notoSansCham,
      // 'Noto Sans Cherokee': FontFamilies.notoSansCherokee,
      // 'Noto Sans Coptic': FontFamilies.notoSansCoptic,
      // 'Noto Sans Cuneiform': FontFamilies.notoSansCuneiform,
      // 'Noto Sans Cypriot': FontFamilies.notoSansCypriot,
      // 'Noto Sans Deseret': FontFamilies.notoSansDeseret,
      // 'Noto Sans Devanagari': FontFamilies.notoSansDevanagari,
      // 'Noto Sans Display': FontFamilies.notoSansDisplay,
      // 'Noto Sans Duployan': FontFamilies.notoSansDuployan,
      // 'Noto Sans Egyptian Hieroglyphs':
      //     FontFamilies.notoSansEgyptianHieroglyphs,
      // 'Noto Sans Elbasan': FontFamilies.notoSansElbasan,
      // 'Noto Sans Elymaic': FontFamilies.notoSansElymaic,
      // 'Noto Sans Georgian': FontFamilies.notoSansGeorgian,
      // 'Noto Sans Glagolitic': FontFamilies.notoSansGlagolitic,
      // 'Noto Sans Gothic': FontFamilies.notoSansGothic,
      // 'Noto Sans Grantha': FontFamilies.notoSansGrantha,
      // 'Noto Sans Gujarati': FontFamilies.notoSansGujarati,
      // 'Noto Sans Gunjala Gondi': FontFamilies.notoSansGunjalaGondi,
      // 'Noto Sans Gurmukhi': FontFamilies.notoSansGurmukhi,
      // 'Noto Sans Hanifi Rohingya': FontFamilies.notoSansHanifiRohingya,
      // 'Noto Sans Hanunoo': FontFamilies.notoSansHanunoo,
      // 'Noto Sans Hatran': FontFamilies.notoSansHatran,
      // 'Noto Sans Hebrew': FontFamilies.notoSansHebrew,
      // 'Noto Sans Imperial Aramaic': FontFamilies.notoSansImperialAramaic,
      // 'Noto Sans Indic Siyaq Numbers': FontFamilies.notoSansIndicSiyaqNumbers,
      // 'Noto Sans Inscriptional Pahlavi':
      //     FontFamilies.notoSansInscriptionalPahlavi,
      // 'Noto Sans Inscriptional Parthian':
      //     FontFamilies.notoSansInscriptionalParthian,
      // 'Noto Sans Javanese': FontFamilies.notoSansJavanese,
      // 'Noto Sans Kaithi': FontFamilies.notoSansKaithi,
      // 'Noto Sans Kannada': FontFamilies.notoSansKannada,
      // 'Noto Sans Kayah Li': FontFamilies.notoSansKayahLi,
      // 'Noto Sans Kharoshthi': FontFamilies.notoSansKharoshthi,
      // 'Noto Sans Khmer': FontFamilies.notoSansKhmer,
      // 'Noto Sans Khojki': FontFamilies.notoSansKhojki,
      // 'Noto Sans Khudawadi': FontFamilies.notoSansKhudawadi,
      // 'Noto Sans Lao': FontFamilies.notoSansLao,
      // 'Noto Sans Lepcha': FontFamilies.notoSansLepcha,
      // 'Noto Sans Limbu': FontFamilies.notoSansLimbu,
      // 'Noto Sans Linear A': FontFamilies.notoSansLinearA,
      // 'Noto Sans Linear B': FontFamilies.notoSansLinearB,
      // 'Noto Sans Lisu': FontFamilies.notoSansLisu,
      // 'Noto Sans Lycian': FontFamilies.notoSansLycian,
      // 'Noto Sans Lydian': FontFamilies.notoSansLydian,
      // 'Noto Sans Mahajani': FontFamilies.notoSansMahajani,
      // 'Noto Sans Malayalam': FontFamilies.notoSansMalayalam,
      // 'Noto Sans Mandaic': FontFamilies.notoSansMandaic,
      // 'Noto Sans Manichaean': FontFamilies.notoSansManichaean,
      // 'Noto Sans Marchen': FontFamilies.notoSansMarchen,
      // 'Noto Sans Masaram Gondi': FontFamilies.notoSansMasaramGondi,
      // 'Noto Sans Math': FontFamilies.notoSansMath,
      // 'Noto Sans Mayan Numerals': FontFamilies.notoSansMayanNumerals,
      // 'Noto Sans Medefaidrin': FontFamilies.notoSansMedefaidrin,
      // 'Noto Sans Meetei Mayek': FontFamilies.notoSansMeeteiMayek,
      // 'Noto Sans Meroitic': FontFamilies.notoSansMeroitic,
      // 'Noto Sans Miao': FontFamilies.notoSansMiao,
      // 'Noto Sans Modi': FontFamilies.notoSansModi,
      // 'Noto Sans Mongolian': FontFamilies.notoSansMongolian,
      // 'Noto Sans Mono': FontFamilies.notoSansMono,
      // 'Noto Sans Mro': FontFamilies.notoSansMro,
      // 'Noto Sans Multani': FontFamilies.notoSansMultani,
      // 'Noto Sans Myanmar': FontFamilies.notoSansMyanmar,
      // 'Noto Sans N Ko': FontFamilies.notoSansNKo,
      // 'Noto Sans Nabataean': FontFamilies.notoSansNabataean,
      // 'Noto Sans New Tai Lue': FontFamilies.notoSansNewTaiLue,
      // 'Noto Sans Newa': FontFamilies.notoSansNewa,
      // 'Noto Sans Nushu': FontFamilies.notoSansNushu,
      // 'Noto Sans Ogham': FontFamilies.notoSansOgham,
      // 'Noto Sans Ol Chiki': FontFamilies.notoSansOlChiki,
      // 'Noto Sans Old Hungarian': FontFamilies.notoSansOldHungarian,
      // 'Noto Sans Old Italic': FontFamilies.notoSansOldItalic,
      // 'Noto Sans Old North Arabian': FontFamilies.notoSansOldNorthArabian,
      // 'Noto Sans Old Permic': FontFamilies.notoSansOldPermic,
      // 'Noto Sans Old Persian': FontFamilies.notoSansOldPersian,
      // 'Noto Sans Old Sogdian': FontFamilies.notoSansOldSogdian,
      // 'Noto Sans Old South Arabian': FontFamilies.notoSansOldSouthArabian,
      // 'Noto Sans Old Turkic': FontFamilies.notoSansOldTurkic,
      // 'Noto Sans Oriya': FontFamilies.notoSansOriya,
      // 'Noto Sans Osage': FontFamilies.notoSansOsage,
      // 'Noto Sans Osmanya': FontFamilies.notoSansOsmanya,
      // 'Noto Sans Pahawh Hmong': FontFamilies.notoSansPahawhHmong,
      // 'Noto Sans Palmyrene': FontFamilies.notoSansPalmyrene,
      // 'Noto Sans Pau Cin Hau': FontFamilies.notoSansPauCinHau,
      // 'Noto Sans Phags Pa': FontFamilies.notoSansPhagsPa,
      // 'Noto Sans Phoenician': FontFamilies.notoSansPhoenician,
      // 'Noto Sans Psalter Pahlavi': FontFamilies.notoSansPsalterPahlavi,
      // 'Noto Sans Rejang': FontFamilies.notoSansRejang,
      // 'Noto Sans Runic': FontFamilies.notoSansRunic,
      // 'Noto Sans Samaritan': FontFamilies.notoSansSamaritan,
      // 'Noto Sans Saurashtra': FontFamilies.notoSansSaurashtra,
      // 'Noto Sans Sharada': FontFamilies.notoSansSharada,
      // 'Noto Sans Shavian': FontFamilies.notoSansShavian,
      // 'Noto Sans Siddham': FontFamilies.notoSansSiddham,
      // 'Noto Sans Sinhala': FontFamilies.notoSansSinhala,
      // 'Noto Sans Sogdian': FontFamilies.notoSansSogdian,
      // 'Noto Sans Sora Sompeng': FontFamilies.notoSansSoraSompeng,
      // 'Noto Sans Soyombo': FontFamilies.notoSansSoyombo,
      // 'Noto Sans Sundanese': FontFamilies.notoSansSundanese,
      // 'Noto Sans Syloti Nagri': FontFamilies.notoSansSylotiNagri,
      // 'Noto Sans Symbols': FontFamilies.notoSansSymbols,
      // 'Noto Sans Symbols 2': FontFamilies.notoSansSymbols2,
      // 'Noto Sans Syriac': FontFamilies.notoSansSyriac,
      // 'Noto Sans Tagalog': FontFamilies.notoSansTagalog,
      // 'Noto Sans Tagbanwa': FontFamilies.notoSansTagbanwa,
      // 'Noto Sans Tai Le': FontFamilies.notoSansTaiLe,
      // 'Noto Sans Tai Tham': FontFamilies.notoSansTaiTham,
      // 'Noto Sans Tai Viet': FontFamilies.notoSansTaiViet,
      // 'Noto Sans Takri': FontFamilies.notoSansTakri,
      // 'Noto Sans Tamil': FontFamilies.notoSansTamil,
      // 'Noto Sans Tamil Supplement': FontFamilies.notoSansTamilSupplement,
      // 'Noto Sans Telugu': FontFamilies.notoSansTelugu,
      // 'Noto Sans Thaana': FontFamilies.notoSansThaana,
      // 'Noto Sans Thai': FontFamilies.notoSansThai,
      // 'Noto Sans Thai Looped': FontFamilies.notoSansThaiLooped,
      // 'Noto Sans Tifinagh': FontFamilies.notoSansTifinagh,
      // 'Noto Sans Tirhuta': FontFamilies.notoSansTirhuta,
      // 'Noto Sans Ugaritic': FontFamilies.notoSansUgaritic,
      // 'Noto Sans Vai': FontFamilies.notoSansVai,
      // 'Noto Sans Wancho': FontFamilies.notoSansWancho,
      // 'Noto Sans Warang Citi': FontFamilies.notoSansWarangCiti,
      // 'Noto Sans Yi': FontFamilies.notoSansYi,
      // 'Noto Sans Zanabazar Square': FontFamilies.notoSansZanabazarSquare,
      // 'Noto Serif': FontFamilies.notoSerif,
      // 'Noto Serif Ahom': FontFamilies.notoSerifAhom,
      // 'Noto Serif Armenian': FontFamilies.notoSerifArmenian,
      // 'Noto Serif Balinese': FontFamilies.notoSerifBalinese,
      // 'Noto Serif Bengali': FontFamilies.notoSerifBengali,
      // 'Noto Serif Devanagari': FontFamilies.notoSerifDevanagari,
      // 'Noto Serif Display': FontFamilies.notoSerifDisplay,
      // 'Noto Serif Dogra': FontFamilies.notoSerifDogra,
      // 'Noto Serif Ethiopic': FontFamilies.notoSerifEthiopic,
      // 'Noto Serif Georgian': FontFamilies.notoSerifGeorgian,
      // 'Noto Serif Grantha': FontFamilies.notoSerifGrantha,
      // 'Noto Serif Gujarati': FontFamilies.notoSerifGujarati,
      // 'Noto Serif Gurmukhi': FontFamilies.notoSerifGurmukhi,
      // 'Noto Serif Hebrew': FontFamilies.notoSerifHebrew,
      // 'Noto Serif Kannada': FontFamilies.notoSerifKannada,
      // 'Noto Serif Khmer': FontFamilies.notoSerifKhmer,
      // 'Noto Serif Lao': FontFamilies.notoSerifLao,
      // 'Noto Serif Malayalam': FontFamilies.notoSerifMalayalam,
      // 'Noto Serif Myanmar': FontFamilies.notoSerifMyanmar,
      // 'Noto Serif Nyiakeng Puachue Hmong':
      //     FontFamilies.notoSerifNyiakengPuachueHmong,
      // 'Noto Serif Sinhala': FontFamilies.notoSerifSinhala,
      // 'Noto Serif Tamil': FontFamilies.notoSerifTamil,
      // 'Noto Serif Tangut': FontFamilies.notoSerifTangut,
      // 'Noto Serif Telugu': FontFamilies.notoSerifTelugu,
      // 'Noto Serif Thai': FontFamilies.notoSerifThai,
      // 'Noto Serif Tibetan': FontFamilies.notoSerifTibetan,
      // 'Noto Serif Yezidi': FontFamilies.notoSerifYezidi,
      // 'Noto Traditional Nushu': FontFamilies.notoTraditionalNushu,
      // 'Nova Cut': FontFamilies.novaCut,
      // 'Nova Flat': FontFamilies.novaFlat,
      // 'Nova Mono': FontFamilies.novaMono,
      // 'Nova Oval': FontFamilies.novaOval,
      // 'Nova Round': FontFamilies.novaRound,
      // 'Nova Script': FontFamilies.novaScript,
      // 'Nova Slim': FontFamilies.novaSlim,
      // 'Nova Square': FontFamilies.novaSquare,
      // 'Numans': FontFamilies.numans,
      // 'Nunito': FontFamilies.nunito,
      // 'Nunito Sans': FontFamilies.nunitoSans,
      // 'Odibee Sans': FontFamilies.odibeeSans,
      // 'Odor Mean Chey': FontFamilies.odorMeanChey,
      // 'Offside': FontFamilies.offside,
      // 'Oi': FontFamilies.oi,
      // 'Old Standard TT': FontFamilies.oldStandardTt,
      // 'Oldenburg': FontFamilies.oldenburg,
      // 'Ole': FontFamilies.ole,
      // 'Oleo Script': FontFamilies.oleoScript,
      // 'Oleo Script Swash Caps': FontFamilies.oleoScriptSwashCaps,
      // 'Oooh Baby': FontFamilies.ooohBaby,
      'Open Sans': FontFamilies.openSans,
      // 'Open Sans Condensed': FontFamilies.openSansCondensed,
      // 'Oranienbaum': FontFamilies.oranienbaum,
      // 'Orbitron': FontFamilies.orbitron,
      // 'Oregano': FontFamilies.oregano,
      // 'Orelega One': FontFamilies.orelegaOne,
      // 'Orienta': FontFamilies.orienta,
      // 'Original Surfer': FontFamilies.originalSurfer,
      // 'Oswald': FontFamilies.oswald,
      // 'Otomanopee One': FontFamilies.otomanopeeOne,
      // 'Outfit': FontFamilies.outfit,
      // 'Over the Rainbow': FontFamilies.overTheRainbow,
      // 'Overlock': FontFamilies.overlock,
      // 'Overlock SC': FontFamilies.overlockSc,
      // 'Overpass': FontFamilies.overpass,
      // 'Overpass Mono': FontFamilies.overpassMono,
      // 'Ovo': FontFamilies.ovo,
      // 'Oxanium': FontFamilies.oxanium,
      // 'Oxygen': FontFamilies.oxygen,
      // 'Oxygen Mono': FontFamilies.oxygenMono,
      // 'PT Mono': FontFamilies.ptMono,
      // 'PT Sans': FontFamilies.ptSans,
      // 'PT Sans Caption': FontFamilies.ptSansCaption,
      // 'PT Sans Narrow': FontFamilies.ptSansNarrow,
      // 'PT Serif': FontFamilies.ptSerif,
      // 'PT Serif Caption': FontFamilies.ptSerifCaption,
      // 'Pacifico': FontFamilies.pacifico,
      // 'Padauk': FontFamilies.padauk,
      // 'Palanquin': FontFamilies.palanquin,
      // 'Palanquin Dark': FontFamilies.palanquinDark,
      // 'Palette Mosaic': FontFamilies.paletteMosaic,
      // 'Pangolin': FontFamilies.pangolin,
      // 'Paprika': FontFamilies.paprika,
      // 'Parisienne': FontFamilies.parisienne,
      // 'Passero One': FontFamilies.passeroOne,
      // 'Passion One': FontFamilies.passionOne,
      // 'Passions Conflict': FontFamilies.passionsConflict,
      // 'Pathway Gothic One': FontFamilies.pathwayGothicOne,
      // 'Patrick Hand': FontFamilies.patrickHand,
      // 'Patrick Hand SC': FontFamilies.patrickHandSc,
      // 'Pattaya': FontFamilies.pattaya,
      // 'Patua One': FontFamilies.patuaOne,
      // 'Pavanam': FontFamilies.pavanam,
      // 'Paytone One': FontFamilies.paytoneOne,
      // 'Peddana': FontFamilies.peddana,
      // 'Peralta': FontFamilies.peralta,
      // 'Permanent Marker': FontFamilies.permanentMarker,
      // 'Petemoss': FontFamilies.petemoss,
      // 'Petit Formal Script': FontFamilies.petitFormalScript,
      // 'Petrona': FontFamilies.petrona,
      // 'Philosopher': FontFamilies.philosopher,
      // 'Piazzolla': FontFamilies.piazzolla,
      // 'Piedra': FontFamilies.piedra,
      // 'Pinyon Script': FontFamilies.pinyonScript,
      // 'Pirata One': FontFamilies.pirataOne,
      // 'Plaster': FontFamilies.plaster,
      // 'Play': FontFamilies.play,
      // 'Playball': FontFamilies.playball,
      // 'Playfair Display': FontFamilies.playfairDisplay,
      // 'Playfair Display SC': FontFamilies.playfairDisplaySc,
      // 'Plus Jakarta Sans': FontFamilies.plusJakartaSans,
      // 'Podkova': FontFamilies.podkova,
      // 'Poiret One': FontFamilies.poiretOne,
      // 'Poller One': FontFamilies.pollerOne,
      // 'Poly': FontFamilies.poly,
      // 'Pompiere': FontFamilies.pompiere,
      // 'Pontano Sans': FontFamilies.pontanoSans,
      // 'Poor Story': FontFamilies.poorStory,
      'Poppins': FontFamilies.poppins,
      // 'Port Lligat Sans': FontFamilies.portLligatSans,
      // 'Port Lligat Slab': FontFamilies.portLligatSlab,
      // 'Potta One': FontFamilies.pottaOne,
      // 'Pragati Narrow': FontFamilies.pragatiNarrow,
      // 'Praise': FontFamilies.praise,
      // 'Prata': FontFamilies.prata,
      // 'Preahvihear': FontFamilies.preahvihear,
      // 'Press Start 2P': FontFamilies.pressStart2p,
      // 'Pridi': FontFamilies.pridi,
      // 'Princess Sofia': FontFamilies.princessSofia,
      // 'Prociono': FontFamilies.prociono,
      // 'Prompt': FontFamilies.prompt,
      // 'Prosto One': FontFamilies.prostoOne,
      // 'Proza Libre': FontFamilies.prozaLibre,
      // 'Public Sans': FontFamilies.publicSans,
      // 'Puppies Play': FontFamilies.puppiesPlay,
      // 'Puritan': FontFamilies.puritan,
      // 'Purple Purse': FontFamilies.purplePurse,
      // 'Qahiri': FontFamilies.qahiri,
      // 'Quando': FontFamilies.quando,
      // 'Quantico': FontFamilies.quantico,
      // 'Quattrocento': FontFamilies.quattrocento,
      // 'Quattrocento Sans': FontFamilies.quattrocentoSans,
      // 'Questrial': FontFamilies.questrial,
      // 'Quicksand': FontFamilies.quicksand,
      // 'Quintessential': FontFamilies.quintessential,
      // 'Qwigley': FontFamilies.qwigley,
      // 'Qwitcher Grypen': FontFamilies.qwitcherGrypen,
      // 'Racing Sans One': FontFamilies.racingSansOne,
      // 'Radio Canada': FontFamilies.radioCanada,
      // 'Radley': FontFamilies.radley,
      // 'Rajdhani': FontFamilies.rajdhani,
      // 'Rakkas': FontFamilies.rakkas,
      'Raleway': FontFamilies.raleway,
      // 'Raleway Dots': FontFamilies.ralewayDots,
      // 'Ramabhadra': FontFamilies.ramabhadra,
      // 'Ramaraja': FontFamilies.ramaraja,
      // 'Rambla': FontFamilies.rambla,
      // 'Rammetto One': FontFamilies.rammettoOne,
      // 'Rampart One': FontFamilies.rampartOne,
      // 'Ranchers': FontFamilies.ranchers,
      // 'Rancho': FontFamilies.rancho,
      // 'Ranga': FontFamilies.ranga,
      // 'Rasa': FontFamilies.rasa,
      // 'Rationale': FontFamilies.rationale,
      // 'Ravi Prakash': FontFamilies.raviPrakash,
      // 'Readex Pro': FontFamilies.readexPro,
      // 'Recursive': FontFamilies.recursive,
      // 'Red Hat Display': FontFamilies.redHatDisplay,
      // 'Red Hat Mono': FontFamilies.redHatMono,
      // 'Red Hat Text': FontFamilies.redHatText,
      // 'Red Rose': FontFamilies.redRose,
      // 'Redacted': FontFamilies.redacted,
      // 'Redacted Script': FontFamilies.redactedScript,
      // 'Redressed': FontFamilies.redressed,
      // 'Reem Kufi': FontFamilies.reemKufi,
      // 'Reenie Beanie': FontFamilies.reenieBeanie,
      // 'Reggae One': FontFamilies.reggaeOne,
      // 'Revalia': FontFamilies.revalia,
      // 'Rhodium Libre': FontFamilies.rhodiumLibre,
      // 'Ribeye': FontFamilies.ribeye,
      // 'Ribeye Marrow': FontFamilies.ribeyeMarrow,
      // 'Righteous': FontFamilies.righteous,
      // 'Risque': FontFamilies.risque,
      // 'Road Rage': FontFamilies.roadRage,
      // 'Roboto': FontFamilies.roboto,
      // 'Roboto Condensed': FontFamilies.robotoCondensed,
      // 'Roboto Flex': FontFamilies.robotoFlex,
      // 'Roboto Mono': FontFamilies.robotoMono,
      // 'Roboto Serif': FontFamilies.robotoSerif,
      // 'Roboto Slab': FontFamilies.robotoSlab,
      // 'Rochester': FontFamilies.rochester,
      // 'Rock 3D': FontFamilies.rock3d,
      // 'Rock Salt': FontFamilies.rockSalt,
      // 'RocknRoll One': FontFamilies.rocknRollOne,
      // 'Rokkitt': FontFamilies.rokkitt,
      // 'Romanesco': FontFamilies.romanesco,
      // 'Ropa Sans': FontFamilies.ropaSans,
      // 'Rosario': FontFamilies.rosario,
      // 'Rosarivo': FontFamilies.rosarivo,
      // 'Rouge Script': FontFamilies.rougeScript,
      // 'Rowdies': FontFamilies.rowdies,
      // 'Rozha One': FontFamilies.rozhaOne,
      // 'Rubik': FontFamilies.rubik,
      // 'Rubik Beastly': FontFamilies.rubikBeastly,
      // 'Rubik Bubbles': FontFamilies.rubikBubbles,
      // 'Rubik Glitch': FontFamilies.rubikGlitch,
      // 'Rubik Microbe': FontFamilies.rubikMicrobe,
      // 'Rubik Mono One': FontFamilies.rubikMonoOne,
      // 'Rubik Moonrocks': FontFamilies.rubikMoonrocks,
      // 'Rubik Puddles': FontFamilies.rubikPuddles,
      // 'Rubik Wet Paint': FontFamilies.rubikWetPaint,
      // 'Ruda': FontFamilies.ruda,
      // 'Rufina': FontFamilies.rufina,
      // 'Ruge Boogie': FontFamilies.rugeBoogie,
      // 'Ruluko': FontFamilies.ruluko,
      // 'Rum Raisin': FontFamilies.rumRaisin,
      // 'Ruslan Display': FontFamilies.ruslanDisplay,
      // 'Russo One': FontFamilies.russoOne,
      // 'Ruthie': FontFamilies.ruthie,
      // 'Rye': FontFamilies.rye,
      // 'STIX Two Text': FontFamilies.stixTwoText,
      // 'Sacramento': FontFamilies.sacramento,
      // 'Sahitya': FontFamilies.sahitya,
      // 'Sail': FontFamilies.sail,
      // 'Saira': FontFamilies.saira,
      // 'Saira Condensed': FontFamilies.sairaCondensed,
      // 'Saira Extra Condensed': FontFamilies.sairaExtraCondensed,
      // 'Saira Semi Condensed': FontFamilies.sairaSemiCondensed,
      // 'Saira Stencil One': FontFamilies.sairaStencilOne,
      // 'Salsa': FontFamilies.salsa,
      // 'Sanchez': FontFamilies.sanchez,
      // 'Sancreek': FontFamilies.sancreek,
      // 'Sansita': FontFamilies.sansita,
      // 'Sansita Swashed': FontFamilies.sansitaSwashed,
      // 'Sarabun': FontFamilies.sarabun,
      // 'Sarala': FontFamilies.sarala,
      // 'Sarina': FontFamilies.sarina,
      // 'Sarpanch': FontFamilies.sarpanch,
      // 'Sassy Frass': FontFamilies.sassyFrass,
      // 'Satisfy': FontFamilies.satisfy,
      // 'Sawarabi Gothic': FontFamilies.sawarabiGothic,
      // 'Sawarabi Mincho': FontFamilies.sawarabiMincho,
      // 'Scada': FontFamilies.scada,
      // 'Scheherazade New': FontFamilies.scheherazadeNew,
      // 'Schoolbell': FontFamilies.schoolbell,
      // 'Scope One': FontFamilies.scopeOne,
      // 'Seaweed Script': FontFamilies.seaweedScript,
      // 'Secular One': FontFamilies.secularOne,
      // 'Sedgwick Ave': FontFamilies.sedgwickAve,
      // 'Sedgwick Ave Display': FontFamilies.sedgwickAveDisplay,
      // 'Sen': FontFamilies.sen,
      // 'Send Flowers': FontFamilies.sendFlowers,
      // 'Sevillana': FontFamilies.sevillana,
      // 'Seymour One': FontFamilies.seymourOne,
      // 'Shadows Into Light': FontFamilies.shadowsIntoLight,
      // 'Shadows Into Light Two': FontFamilies.shadowsIntoLightTwo,
      // 'Shalimar': FontFamilies.shalimar,
      // 'Shanti': FontFamilies.shanti,
      // 'Share': FontFamilies.share,
      // 'Share Tech': FontFamilies.shareTech,
      // 'Share Tech Mono': FontFamilies.shareTechMono,
      // 'Shippori Antique': FontFamilies.shipporiAntique,
      // 'Shippori Antique B1': FontFamilies.shipporiAntiqueB1,
      // 'Shippori Mincho': FontFamilies.shipporiMincho,
      // 'Shippori Mincho B1': FontFamilies.shipporiMinchoB1,
      // 'Shizuru': FontFamilies.shizuru,
      // 'Shojumaru': FontFamilies.shojumaru,
      // 'Short Stack': FontFamilies.shortStack,
      // 'Shrikhand': FontFamilies.shrikhand,
      // 'Siemreap': FontFamilies.siemreap,
      // 'Sigmar One': FontFamilies.sigmarOne,
      // 'Signika': FontFamilies.signika,
      // 'Signika Negative': FontFamilies.signikaNegative,
      // 'Simonetta': FontFamilies.simonetta,
      // 'Single Day': FontFamilies.singleDay,
      // 'Sintony': FontFamilies.sintony,
      // 'Sirin Stencil': FontFamilies.sirinStencil,
      // 'Six Caps': FontFamilies.sixCaps,
      // 'Skranji': FontFamilies.skranji,
      // 'Slabo 13px': FontFamilies.slabo13px,
      // 'Slabo 27px': FontFamilies.slabo27px,
      // 'Slackey': FontFamilies.slackey,
      // 'Smokum': FontFamilies.smokum,
      // 'Smooch': FontFamilies.smooch,
      // 'Smooch Sans': FontFamilies.smoochSans,
      // 'Smythe': FontFamilies.smythe,
      // 'Sniglet': FontFamilies.sniglet,
      // 'Snippet': FontFamilies.snippet,
      // 'Snowburst One': FontFamilies.snowburstOne,
      // 'Sofadi One': FontFamilies.sofadiOne,
      // 'Sofia': FontFamilies.sofia,
      // 'Solway': FontFamilies.solway,
      // 'Song Myung': FontFamilies.songMyung,
      // 'Sonsie One': FontFamilies.sonsieOne,
      // 'Sora': FontFamilies.sora,
      // 'Sorts Mill Goudy': FontFamilies.sortsMillGoudy,
      // 'Source Code Pro': FontFamilies.sourceCodePro,
      // 'Source Sans 3': FontFamilies.sourceSans3,
      // 'Source Sans Pro': FontFamilies.sourceSansPro,
      // 'Source Serif 4': FontFamilies.sourceSerif4,
      // 'Source Serif Pro': FontFamilies.sourceSerifPro,
      // 'Space Grotesk': FontFamilies.spaceGrotesk,
      // 'Space Mono': FontFamilies.spaceMono,
      // 'Special Elite': FontFamilies.specialElite,
      // 'Spectral': FontFamilies.spectral,
      // 'Spectral SC': FontFamilies.spectralSc,
      // 'Spicy Rice': FontFamilies.spicyRice,
      // 'Spinnaker': FontFamilies.spinnaker,
      // 'Spirax': FontFamilies.spirax,
      // 'Spline Sans': FontFamilies.splineSans,
      // 'Squada One': FontFamilies.squadaOne,
      // 'Square Peg': FontFamilies.squarePeg,
      // 'Sree Krushnadevaraya': FontFamilies.sreeKrushnadevaraya,
      // 'Sriracha': FontFamilies.sriracha,
      // 'Srisakdi': FontFamilies.srisakdi,
      // 'Staatliches': FontFamilies.staatliches,
      // 'Stalemate': FontFamilies.stalemate,
      // 'Stalinist One': FontFamilies.stalinistOne,
      // 'Stardos Stencil': FontFamilies.stardosStencil,
      // 'Stick': FontFamilies.stick,
      // 'Stick No Bills': FontFamilies.stickNoBills,
      // 'Stint Ultra Condensed': FontFamilies.stintUltraCondensed,
      // 'Stint Ultra Expanded': FontFamilies.stintUltraExpanded,
      // 'Stoke': FontFamilies.stoke,
      // 'Strait': FontFamilies.strait,
      // 'Style Script': FontFamilies.styleScript,
      // 'Stylish': FontFamilies.stylish,
      // 'Sue Ellen Francisco': FontFamilies.sueEllenFrancisco,
      // 'Suez One': FontFamilies.suezOne,
      // 'Sulphur Point': FontFamilies.sulphurPoint,
      // 'Sumana': FontFamilies.sumana,
      // 'Sunflower': FontFamilies.sunflower,
      // 'Sunshiney': FontFamilies.sunshiney,
      // 'Supermercado One': FontFamilies.supermercadoOne,
      // 'Sura': FontFamilies.sura,
      // 'Suranna': FontFamilies.suranna,
      // 'Suravaram': FontFamilies.suravaram,
      // 'Suwannaphum': FontFamilies.suwannaphum,
      // 'Swanky and Moo Moo': FontFamilies.swankyAndMooMoo,
      // 'Syncopate': FontFamilies.syncopate,
      // 'Syne': FontFamilies.syne,
      // 'Syne Mono': FontFamilies.syneMono,
      // 'Syne Tactile': FontFamilies.syneTactile,
      // 'Tajawal': FontFamilies.tajawal,
      // 'Tangerine': FontFamilies.tangerine,
      // 'Tapestry': FontFamilies.tapestry,
      // 'Taprom': FontFamilies.taprom,
      // 'Tauri': FontFamilies.tauri,
      // 'Taviraj': FontFamilies.taviraj,
      // 'Teko': FontFamilies.teko,
      // 'Telex': FontFamilies.telex,
      // 'Tenali Ramakrishna': FontFamilies.tenaliRamakrishna,
      // 'Tenor Sans': FontFamilies.tenorSans,
      // 'Text Me One': FontFamilies.textMeOne,
      // 'Texturina': FontFamilies.texturina,
      // 'Thasadith': FontFamilies.thasadith,
      // 'The Girl Next Door': FontFamilies.theGirlNextDoor,
      // 'The Nautigal': FontFamilies.theNautigal,
      // 'Tienne': FontFamilies.tienne,
      // 'Tillana': FontFamilies.tillana,
      // 'Timmana': FontFamilies.timmana,
      // 'Tinos': FontFamilies.tinos,
      // 'Titan One': FontFamilies.titanOne,
      // 'Titillium Web': FontFamilies.titilliumWeb,
      // 'Tomorrow': FontFamilies.tomorrow,
      // 'Tourney': FontFamilies.tourney,
      // 'Trade Winds': FontFamilies.tradeWinds,
      // 'Train One': FontFamilies.trainOne,
      // 'Trirong': FontFamilies.trirong,
      // 'Trispace': FontFamilies.trispace,
      // 'Trocchi': FontFamilies.trocchi,
      // 'Trochut': FontFamilies.trochut,
      // 'Truculenta': FontFamilies.truculenta,
      // 'Trykker': FontFamilies.trykker,
      // 'Tulpen One': FontFamilies.tulpenOne,
      // 'Turret Road': FontFamilies.turretRoad,
      // 'Twinkle Star': FontFamilies.twinkleStar,
      // 'Ubuntu': FontFamilies.ubuntu,
      // 'Ubuntu Condensed': FontFamilies.ubuntuCondensed,
      // 'Ubuntu Mono': FontFamilies.ubuntuMono,
      // 'Uchen': FontFamilies.uchen,
      // 'Ultra': FontFamilies.ultra,
      // 'Uncial Antiqua': FontFamilies.uncialAntiqua,
      // 'Underdog': FontFamilies.underdog,
      // 'Unica One': FontFamilies.unicaOne,
      // 'UnifrakturCook': FontFamilies.unifrakturCook,
      // 'UnifrakturMaguntia': FontFamilies.unifrakturMaguntia,
      // 'Unkempt': FontFamilies.unkempt,
      // 'Unlock': FontFamilies.unlock,
      // 'Unna': FontFamilies.unna,
      // 'Updock': FontFamilies.updock,
      // 'Urbanist': FontFamilies.urbanist,
      // 'VT323': FontFamilies.vt323,
      // 'Vampiro One': FontFamilies.vampiroOne,
      // 'Varela': FontFamilies.varela,
      // 'Varela Round': FontFamilies.varelaRound,
      // 'Varta': FontFamilies.varta,
      // 'Vast Shadow': FontFamilies.vastShadow,
      // 'Vazirmatn': FontFamilies.vazirmatn,
      // 'Vesper Libre': FontFamilies.vesperLibre,
      // 'Viaoda Libre': FontFamilies.viaodaLibre,
      // 'Vibes': FontFamilies.vibes,
      // 'Vibur': FontFamilies.vibur,
      // 'Vidaloka': FontFamilies.vidaloka,
      // 'Viga': FontFamilies.viga,
      // 'Voces': FontFamilies.voces,
      // 'Volkhov': FontFamilies.volkhov,
      // 'Vollkorn': FontFamilies.vollkorn,
      // 'Vollkorn SC': FontFamilies.vollkornSc,
      // 'Voltaire': FontFamilies.voltaire,
      // 'Vujahday Script': FontFamilies.vujahdayScript,
      // 'Waiting for the Sunrise': FontFamilies.waitingForTheSunrise,
      // 'Wallpoet': FontFamilies.wallpoet,
      // 'Walter Turncoat': FontFamilies.walterTurncoat,
      // 'Warnes': FontFamilies.warnes,
      // 'Water Brush': FontFamilies.waterBrush,
      // 'Waterfall': FontFamilies.waterfall,
      // 'Wellfleet': FontFamilies.wellfleet,
      // 'Wendy One': FontFamilies.wendyOne,
      // 'Whisper': FontFamilies.whisper,
      // 'WindSong': FontFamilies.windSong,
      // 'Wire One': FontFamilies.wireOne,
      // 'Work Sans': FontFamilies.workSans,
      // 'Xanh Mono': FontFamilies.xanhMono,
      // 'Yaldevi': FontFamilies.yaldevi,
      // 'Yanone Kaffeesatz': FontFamilies.yanoneKaffeesatz,
      // 'Yantramanav': FontFamilies.yantramanav,
      // 'Yatra One': FontFamilies.yatraOne,
      // 'Yellowtail': FontFamilies.yellowtail,
      // 'Yeon Sung': FontFamilies.yeonSung,
      // 'Yeseva One': FontFamilies.yesevaOne,
      // 'Yesteryear': FontFamilies.yesteryear,
      // 'Yomogi': FontFamilies.yomogi,
      // 'Yrsa': FontFamilies.yrsa,
      // 'Yuji Boku': FontFamilies.yujiBoku,
      // 'Yuji Hentaigana Akari': FontFamilies.yujiHentaiganaAkari,
      // 'Yuji Hentaigana Akebono': FontFamilies.yujiHentaiganaAkebono,
      // 'Yuji Mai': FontFamilies.yujiMai,
      // 'Yuji Syuku': FontFamilies.yujiSyuku,
      // 'Yusei Magic': FontFamilies.yuseiMagic,
      // 'ZCOOL KuaiLe': FontFamilies.zcoolKuaiLe,
      // 'ZCOOL QingKe HuangYou': FontFamilies.zcoolQingKeHuangYou,
      // 'ZCOOL XiaoWei': FontFamilies.zcoolXiaoWei,
      // 'Zen Antique': FontFamilies.zenAntique,
      // 'Zen Antique Soft': FontFamilies.zenAntiqueSoft,
      // 'Zen Dots': FontFamilies.zenDots,
      // 'Zen Kaku Gothic Antique': FontFamilies.zenKakuGothicAntique,
      // 'Zen Kaku Gothic New': FontFamilies.zenKakuGothicNew,
      // 'Zen Kurenaido': FontFamilies.zenKurenaido,
      // 'Zen Loop': FontFamilies.zenLoop,
      // 'Zen Maru Gothic': FontFamilies.zenMaruGothic,
      // 'Zen Old Mincho': FontFamilies.zenOldMincho,
      // 'Zen Tokyo Zoo': FontFamilies.zenTokyoZoo,
      // 'Zeyada': FontFamilies.zeyada,
      // 'Zhi Mang Xing': FontFamilies.zhiMangXing,
      // 'Zilla Slab': FontFamilies.zillaSlab,
      // 'Zilla Slab Highlight': FontFamilies.zillaSlabHighlight,
    };
